container:
  image: python:slim

test_task:
  pip_cache:
    folder: ~/.cache/pip
    populate_script:
    - apt update
    - apt -y install git
    - pip install -e .[testing]
    - pip install pytest
  test_script: pytest
