task:
  container:
    image: node:latest
  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat yarn.lock
    populate_script: yarn install
  matrix:
  - name: Lint
    lint_script: yarn run lint
  - name: Test
    container:
      matrix:
      - image: node:latest
      - image: node:lts
      - image: node:19-alpine
      - image: node:19-bullseye
      - image: node:19-slim
      - image: node:19-buster
      - image: node:18-alpine
      - image: node:18-bullseye
      - image: node:18-slim
      - image: node:18-buster
    test_script: yarn run test
  - name: Publish
    depends_on:
    - Lint
    - Test
    only_if: $BRANCH == "master"
    publish_script: yarn run publish
